### ISSUE TITLE
Notification does not work on Android Version 9

### ISSUE THREAD

**Issue by alissonzubcov** [vel-jack/GodotLocalNotification#1]
Hello Friend.
I tested the plugin and noticed that it is not working on android version 9. Do you have anything to solve?
Thanks for sharing this plugin, it helped a lot.

**Comment by vel-jack** [comment]
I updated the code, please check now

create a `DEFAULT_CHANNEL_ID` and use it like [this](https://github.com/vel-jack/GodotLocalNotification/blob/63d2956aa2678e3a74d42573e04342ab374e9f48/localnotification/src/LocalNotificationReceiver.java#L33)

`NotificationCompat.Builder(context,DEFAULT_CHANNEL_ID)`


Thanks for opening the issue :)

**Comment by alissonzubcov** [comment]
the following error happens:

01-18 17:58:53.014  2017 16186 E NotificationService: No Channel found for pkg=com.example, channelId=10001, id=1, tag=null, opPkg=br.com.example, callingUid=10246, userId=0, incomingUserId=0, notificationUid=10246, notification=Notification(channel=10001 pri=0 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x10 color=0x00000000 vis=PRIVATE)

**Comment by vel-jack** [comment]
@AlissonRichardy  please check now

**Comment by alissonzubcov** [comment]
I tested it now and everything is fine.
Thanks for the work! He had made an implementation but his code was much better.
Once again, thank you for your great work.
